import openai
import os
from dotenv import load_dotenv

load_dotenv()  # Loads your OPENAI_API_KEY from .env file
openai.api_key = os.getenv("OPENAI_API_KEY")

def ask_gpt_about_code(code_snippet):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",  # or "gpt-4" if you have access
            messages=[
                {"role": "system", "content": "You are a code reviewer. Given a Python code snippet, decide if it's written by a human or generated by AI, and explain your reasoning."},
                {"role": "user", "content": code_snippet}
            ]
        )
        return response['choices'][0]['message']['content']
    except Exception as e:
        return f"Error: {str(e)}"

def detect_ai_in_cells(code_cell_groups):
    results = []
    for group in code_cell_groups:
        code = "\n".join(group)
        result = ask_gpt_about_code(code)
        results.append(result)
    return results
